name = "Thaumesque"
author = "Linc Thornmire"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff8008f1c7df1a8342257b8f3e1027f82b3ce9a1ffce6389f99affeda335049c"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12.2"]
